// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SoilReportApp.Infrastructure.Data;

#nullable disable

namespace SoilReportApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SoilReportApp.Domain.Entities.Crop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Crops");
                });

            modelBuilder.Entity("SoilReportApp.Domain.Entities.CropStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CropStages");
                });

            modelBuilder.Entity("SoilReportApp.Domain.Entities.Reading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("K")
                        .HasColumnType("double precision");

                    b.Property<double>("Moisture")
                        .HasColumnType("double precision");

                    b.Property<double>("N")
                        .HasColumnType("double precision");

                    b.Property<double>("P")
                        .HasColumnType("double precision");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("Test")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("Readings");
                });

            modelBuilder.Entity("SoilReportApp.Domain.Entities.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CropId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CropStageId")
                        .HasColumnType("uuid");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ExpertId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FarmerId")
                        .HasColumnType("uuid");

                    b.Property<double>("KAvg")
                        .HasColumnType("double precision");

                    b.Property<double>("MoistureAvg")
                        .HasColumnType("double precision");

                    b.Property<double>("NAvg")
                        .HasColumnType("double precision");

                    b.Property<double>("PAvg")
                        .HasColumnType("double precision");

                    b.Property<string>("Report")
                        .HasColumnType("text");

                    b.Property<Guid?>("SoilTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CropId");

                    b.HasIndex("CropStageId");

                    b.HasIndex("ExpertId");

                    b.HasIndex("FarmerId");

                    b.HasIndex("SoilTypeId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("SoilReportApp.Domain.Entities.SoilType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SoilTypes");
                });

            modelBuilder.Entity("SoilReportApp.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserType")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SoilReportApp.Domain.Entities.Reading", b =>
                {
                    b.HasOne("SoilReportApp.Domain.Entities.Request", "Request")
                        .WithMany("Readings")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("SoilReportApp.Domain.Entities.Request", b =>
                {
                    b.HasOne("SoilReportApp.Domain.Entities.Crop", "Crop")
                        .WithMany("Requests")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SoilReportApp.Domain.Entities.CropStage", "CropStage")
                        .WithMany("Requests")
                        .HasForeignKey("CropStageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SoilReportApp.Domain.Entities.User", "Expert")
                        .WithMany("RequestsAsExpert")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SoilReportApp.Domain.Entities.User", "Farmer")
                        .WithMany("RequestsAsFarmer")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SoilReportApp.Domain.Entities.SoilType", "SoilType")
                        .WithMany("Requests")
                        .HasForeignKey("SoilTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Crop");

                    b.Navigation("CropStage");

                    b.Navigation("Expert");

                    b.Navigation("Farmer");

                    b.Navigation("SoilType");
                });

            modelBuilder.Entity("SoilReportApp.Domain.Entities.Crop", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("SoilReportApp.Domain.Entities.CropStage", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("SoilReportApp.Domain.Entities.Request", b =>
                {
                    b.Navigation("Readings");
                });

            modelBuilder.Entity("SoilReportApp.Domain.Entities.SoilType", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("SoilReportApp.Domain.Entities.User", b =>
                {
                    b.Navigation("RequestsAsExpert");

                    b.Navigation("RequestsAsFarmer");
                });
#pragma warning restore 612, 618
        }
    }
}
